name: dioptric
channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - ipython
  - pip
  - matplotlib
  - numpy
  - openpyxl
  - pillow
  - gitpython
  - pandas 
  - pyqt
  - pathos
  - scipy
  - keyring
  - chardet
  - gcc
  - pip:
      - colorutils
      - nidaqmx
      - pylabrad
      - strenum
      - twisted
      - PyGObject
      - mpmath
